---
# tasks file for onedata.onezone for ubuntu 

#this package is required so that 'become' option worked in ansible 2.*
- name: install setfacl support
  become: yes
  apt: pkg=acl

- include: install.yml 
  tags: onezone, onezone:install
  when: (onezone_install.skipped is undefined) or
        (onezone_defaults.skipped is undefined)

- name: Configure Onezone using Onepanel (this will alwasy be marked as changed)
  script: "{{ onezone_conf_script }}"
  environment:
    ONEPANEL_BATCH_MODE: true
    ONEZONE_CONFIG: "{{ lookup('template', 'single_node.j2') }}"
  tags: onezone,onezone:configure
  when: (onezone_configure.skipped is undefined) or
        (onezone_defaults.skipped is undefined)

- include: uninstall.yml
  tags: onezone:uninstall
  when: onezone_uninstall.skipped is undefined

