---
# uninstall tasks file for onedata.onezone for ubuntu 

- name: Stop all Onezone Services
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: stopped
  with_items:
    - oz-worker
    - oz-panel
    - cluster-manager
  ignore_errors: yes

- name: Uninstall Onezone package
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    force: yes
  with_items:
    - couchbase-server-community
    - oz-worker
    - oz-panel
    - cluster-manager
    - onezone

- name: Delete config files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/oz_panel
    - /usr/lib/oz_panel
    - /usr/lib/oz_worker
    - /var/lib/oz_worker
    - /usr/lib/cluster_manager/
    - /tmp/oz_panel
    - /tmp/oz_worker
    - /tmp/onedata
    - /tmp/cluster_manager
    - /var/lib/cluster_manager
    - /opt/couchbase # remove all Onedata database

- name: Remove Onedata repository key
  apt_key:
    id: "{{ apt_key_id }}"
    url: "{{ apt_key_url }}"
    state: absent

# - name: Remve Onedata repository and update apt cache
#   apt_repository:
#     repo: "{{ apt_repository }}"
#     state: absent
  